tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: buttons
            field:
              type: grid
              display: Buttons
              mode: stacked
              add_row: 'Add Header Button'
              localizable: true
              fields:
                -
                  handle: handle
                  field:
                    type: text
                    display: Handle
                    instructions: 'Stable identifier used by templates to select a specific button.'
                    localizable: false
                    validate:
                      - required
                      - alpha_dash
                    width: 33
                -
                  import: button_with_icon
