tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: image
            field:
              type: assets
              display: Image
              container: assets
              max_files: 1
              localizable: true
              width: 50
          -
            handle: sub_title
            field:
              type: text
              display: 'Sub Title'
              localizable: true
              width: 50
